#Site configuration
title: Helen S. Feng
name: Helen S. Feng
author: Helen Feng
work:  Program Manager
year: 2020

# Navigation
nav1: "About"
nav2: "Toolbox"
nav3: "Projects"

# Section1
sec1: "WELCOME"
sec2: "About"
#sec3: "Faucibus sed lobortis aliquam lorem blandit. Lorem eu nunc metus col. Commodo id in arcu ante lorem ipsum sed accumsan erat praesent faucibus commodo ac mi lacus. Adipiscing mi ac commodo. Vis aliquet tortor ultricies non ante erat nunc integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer non. Adipiscing cubilia elementum."

# Section 2
sec4: "Toolbox"
sec5: "These are the skills and tools I use to get things done. I'm always looking to expand my skill set by learning new concepts and gaining more experience."
icon1: "fa-code"
icont1: "Python, SQL, Git, Fortran"
icon2: "fa-database"
icont2: "Data management"
icon3: "fa-dot-circle-o"
icont3: "Quantitative analysis"
icon4: "fa-line-chart"
icont4: "Data visualization"
icon5: "fa-columns"
icont5: "HTML, CSS"
icon6: "fa-globe"
icont6: "Mandarin, Spanish"

# Section 3
sec6: "Projects"
sec7: "Below are some projects I've been working on. Click on the images to learn more!"
sec8: "IODP Site Data"
sec9: "Automating data collection and reorganization for the IODP website"
sec10: "PhD Research"
sec11: "Seismic constraints on the processes and consequences of secondary igneous evolution of Pacific oceanic lithosphere"
sec12: "Simpsons Database"
sec13: "Analysis of Simpsons scripts"
#sec14: "In Progress"
#sec15: "Will be updated soon"

# Social Links
#facebook: username
#twitter:  username
#google: username
#instagram: username
#pinterest: username
linkedin: helen-s-feng
#youtube: username
#spotify: username
#lastfm: username
github: helenx
#stackoverflow: username
#quora: username
#reddit: username
orcid: 0000-0001-6668-8221
#medium: username
#vimeo: username
#keybase: username
email: helenxxfeng@gmail.com

